### ISSUE TITLE
Add additional Ruby examples

### ISSUE THREAD

**Issue by nathos** [github-services-engineering/api-demos#1]
We should add additional Ruby/Octokit examples to the repository, perhaps borrowing from https://github.com/github/platform-samples

**Comment by nathos** [comment]
I added another example, in this case an organization access script, to the repo in https://github.com/github-services-engineering/api-demos/commit/f3312ae99155021d87fc56b0cf5ff3507d534bae

**Comment by nathos** [comment]
Closing this issue via the API

**Comment by swinton** [comment]
:+1: via the API

**Comment by nathos** [comment]
This is a new comment posted via the GraphQL API
